instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notifications.urls', namespace='notifications')),
    path('', include('directs.urls', namespace='directs')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('profiles.urls', namespace='profiles')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from notifications.views import ShowNotification, DeleteNotification


app_name = 'notifications'

urlpatterns = [
    path('ShowNotification/', ShowNotification, name='show-notification'),
    path('<noti_id>/delete', DeleteNotification, name='delete-notification'),


]

posts/urls.py
from django.urls import path
app_name = 'posts'

from .views import *


urlpatterns = [
    path('',index,name='home'),
    path('newpost/',NewPost,name='newpost'),
    path('<uuid:post_id>', PostDetail, name='post-details'),
    path('<uuid:post_id>/like', like, name='like'),
    path('<uuid:post_id>/favourite', favourite, name='favourite'),
    path('tag/<slug:tag_slug>', Tags, name='tags'),



]

profiles/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
# from authy.views import UserProfile, EditProfile
from .views import UserProfile, follow, EditProfile

app_name ='profiles'

urlpatterns = [
    # Profile Section
    path('profile/edit', EditProfile, name="editprofile"),

    # User Authentication
    path('sign-up/', views.register, name="sign-up"),
    path('sign-in/', auth_views.LoginView.as_view(template_name="user/sign-in.html", redirect_authenticated_user=True), name='sign-in'),
    path('sign-out/', auth_views.LogoutView.as_view(template_name="user/sign-out.html"), name='sign-out'),

    path('<username>/', UserProfile, name='profile'),
    path('<username>/saved/', UserProfile, name='profilefavourite'),
    path('<username>/follow/<option>/', follow, name='follow'),
]

notifications/models.py
from django.db import models
from django.contrib.auth.models import User
# from post.models import Post

class Notification(models.Model):
    NOTIFICATION_TYPES = ((1, 'Like'), (2, 'Comment'), (3, 'Follow'))

    post = models.ForeignKey("posts.Post", on_delete=models.CASCADE, related_name="notification_post", null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notification_from_user" )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notification_to_user" )
    notification_types = models.IntegerField(choices=NOTIFICATION_TYPES, null=True, blank=True)
    text_preview = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.text_preview

notifications/views.py
from django.shortcuts import render, redirect

# Create your views here.
from notifications.models import Notification


def ShowNotification(request):
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date')

    context = {
        'notifications': notifications,

    }
    return render(request, 'notification/notification.html', context)

def DeleteNotification(request, noti_id):
    user = request.user
    Notification.objects.filter(id=noti_id, user=user).delete()
    return redirect('notifications:show-notification')

templates/notification/notification.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script> -->
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Login Form</title>
</head>

<body>

  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        
    

        <form action="" method="POST" enctype="multipart/form-data">
          <div class="logo">
            <h3 style="padding-top: 5px; font-size: 20px;">Notifications</h3>
          </div>

            <!-- First Section -->
            {% for notification in notifications %}
                {% if notification.notification_type == 1 %}
                    <div class="alert alert-white alert-dismissible fade show" role="alert" style="border: 1px rgba(219, 219, 219, 0.699) solid; border-radius: 25px;">
                        <div class="side-menu__user-profile">
                            <a href="{% url 'profiles:profile' user.username %}" class="side-menu__user-avatar">
                                {% if notification.sender.profile.image %}
                                    <img src="{{ notification.sender.profile.image.url }}" alt="User Picture">
                                {% else %}
                                    <img src="{% static 'assets1/default.jpg' %}" alt="User Picture">
                                {% endif %}
                            </a>
                            <div class="side-menu__user-idnfo" style="text-align: start;">
                                <a href="{% url 'profiles:profile' user.username %}" style="font-size: 15px; color: black; text-align: center;">{{ notification.sender.profile.first_name|title }} {{ notification.sender.profile.last_name|title }}</a> <br>
                                <a href="{% url 'profiles:profile' user.username %}" style="font-size: 15px; color: black; text-align: center;"><b><i class="bi bi-hand-thumbs-up-fill" style="color: blue;"></i> Liked you Picture</b></a> <br>
                                <a href="{% url 'profiles:profile' user.username %}" style="font-size: 10px; color: rgb(75, 75, 75); ">{{ notification.date }}</a>

                            </div>
                            <a href="{% url 'profiles:profile' user.username %}" class="side-menu__user-avatar" style="margin-left: 20px;">
                                <img src="{{ notification.post.picture.url }}" alt="User Picture">
                            </a>
                        </div>
                        <a href="{% url 'delete-notification' notification.id %}" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
                      </div>
                {% endif %}
                
                {% if notification.notification_type == 3 %}
                    <div class="alert alert-white alert-dismissible fade show" role="alert" style="border: 1px rgba(219, 219, 219, 0.699) solid; border-radius: 25px;">
                        <div class="side-menu__user-profile">
                            <a href="{% url 'profiles:profile' user.username %}" class="side-menu__user-avatar">
                                {% if notification.sender.profile.image %}
                                    <img src="{{ notification.sender.profile.image.url }}" alt="User Picture">
                                {% else %}
                                    <img src="{% static 'assets1/default.jpg' %}" alt="User Picture">
                                {% endif %}
                            </a>
                            <div class="side-menu__user-idnfo" style="text-align: start;">
                                <a href="{% url 'profile' user.username %}" style="font-size: 15px; color: black; text-align: center;">{{ notification.sender.profile.first_name|title }} {{ notification.sender.profile.last_name|title }}</a> <br>
                                <a href="{% url 'profile' user.username %}" style="font-size: 15px; color: black; text-align: center;"><b><i class="bi bi-hand-thumbs-up-fill" style="color: blue;"></i> Liked you Picture</b></a> <br>
                                <a href="{% url 'profile' user.username %}" style="font-size: 10px; color: rgb(75, 75, 75); ">{{ notification.date }}</a>
                            </div>
                        </div>
                        <a href="{% url 'notifications:delete-notification' notification.id %}" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
                      </div>
                {% endif %}


                {% if notification.notification_type == 2 %}
                <div class="alert alert-white alert-dismissible fade show" role="alert" style="border: 1px rgba(219, 219, 219, 0.699) solid; border-radius: 25px;">
                  <div class="side-menu__user-profile">

                    <a href="{% url 'profiles:profile' user.username %}" class="side-menu__user-avatar">
                      {% if notification.sender.profile.image %}
                          <img src="{{ notification.sender.profile.image.url }}" alt="User Picture">
                      {% else %}
                          <img src="{% static 'assets1/default.jpg' %}" alt="User Picture">
                      {% endif %}
                    </a>
                     
                      <div class="side-menu__user-info" style="text-align: start;">
                        <a href="{% url 'profiles:profile' user.username %}" style="font-size: 15px; color: black; text-align: center;">{{ notification.sender.profile.first_name|title }} {{ notification.sender.profile.last_name|title }}</a> <br>
                        <a href="{% url 'profiles:profile' user.username %}" style="font-size: 15px; color: black; text-align: center;"><b><i class="bi bi-chat-dots-fill" style="color: rgb(252, 122, 1);"></i> Commented on your post</b></a> <br>
                        <a href="{% url 'profiles:profile' user.username %}" style="font-size: 10px; color: rgb(75, 75, 75); ">{{ notification.date }}</a>
                      </div>

                      <a href="{% url 'profiles:profile' user.username %}" class="side-menu__user-avatar" style="margin-left: 20px;">
                        <img src="{{ notification.post.picture.url }}" alt="User Picture">
                      </a>
                  </div>
                  <a href="{% url 'notifications:delete-notification' notification.id %}" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
              </div>
                {% endif %}

            {% endfor %}

            <!-- third Section -->

            

        </form>


      </div>
    </div>

    <footer>
      <div class="container">
        <nav class="footer-nav">
          <ul>
            <li>
              <a href="#">About us</a>
            </li>
            <li>
              <a href="#">Support</a>
            </li>
            <li>
              <a href="#">Press</a>
            </li>
            <li>
              <a href="#">Api</a>
            </li>
            <li>
              <a href="#">Jobs</a>
            </li>
            <li>
              <a href="#">Privacy</a>
            </li>
            <li>
              <a href="#">Terms</a>
            </li>
            <li>
              <a href="#">Directory</a>
            </li>
            <li>
              <a href="#">Profiles</a>
            </li>
            <li>
              <a href="#">Hashtags</a>
            </li>
            <li>
              <a href="#">Languages</a>
            </li>
          </ul>
        </nav>
        <div class="copyright-notice">
          &copy 2023 Instagram
        </div>
      </div>
    </footer>

  </div>

</body>

</html>
{% endblock content %}