directs/urls.py
from directs.views import inbox, Directs, SendDirect, UserSearch, NewConversation
from django.urls import path

app_name = 'directs'

urlpatterns = [
    path('inbox/', inbox, name="message"),
    path('direct/<username>', Directs, name="directs"),
    path('send/', SendDirect, name="send-directs"),
    path('search/', UserSearch, name="search-users"),
    path('new/<username>', NewConversation, name="conversation"),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notifications.urls', namespace='notifications')),
    path('', include('directs.urls', namespace='directs')),
    path('', include('posts.urls', namespace='posts')),
    path('', include('profiles.urls', namespace='profiles')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
app_name = 'posts'

from .views import *


urlpatterns = [
    path('',index,name='home'),
    path('newpost/',NewPost,name='newpost'),
    path('<uuid:post_id>', PostDetail, name='post-details'),
    path('<uuid:post_id>/like', like, name='like'),
    path('<uuid:post_id>/favourite', favourite, name='favourite'),
    path('tag/<slug:tag_slug>', Tags, name='tags'),



]

profiles/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
# from authy.views import UserProfile, EditProfile
from .views import UserProfile, follow, EditProfile

app_name ='profiles'

urlpatterns = [
    # Profile Section
    path('profile/edit', EditProfile, name="editprofile"),

    # User Authentication
    path('sign-up/', views.register, name="sign-up"),
    path('sign-in/', auth_views.LoginView.as_view(template_name="user/sign-in.html", redirect_authenticated_user=True), name='sign-in'),
    path('sign-out/', auth_views.LogoutView.as_view(template_name="user/sign-out.html"), name='sign-out'),

    path('<username>/', UserProfile, name='profile'),
    path('<username>/saved/', UserProfile, name='profilefavourite'),
    path('<username>/follow/<option>/', follow, name='follow'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
import PIL
from PIL import Image
from django.db.models.base import Model
from django.db.models.fields import DateField
from django.urls import reverse
from django.db.models.signals import post_save
import uuid
from django.utils import timezone
from posts.models import Post


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    image = models.ImageField(upload_to="profile_picture", null=True, default="default.jpg")
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    url = models.URLField(max_length=200, null=True, blank=True)
    favourite = models.ManyToManyField(Post, blank=True)

    def __str__(self):
        return f'{self.user.username} - Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

profiles/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class EditProfileForm(forms.ModelForm):
    image = forms.ImageField(required=True)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'First Name'}), required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Last Name'}), required=True)
    bio = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Bio'}), required=True)
    url = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'URL'}), required=True)
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Address'}), required=True)

    class Meta:
        model = Profile
        fields = ['image', 'first_name', 'last_name', 'bio', 'url', 'location']



class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'prompt srch_explore'}), max_length=50, required=True)
    # username = forms.EmailInput(widget=forms.TextInput(attrs={'placeholder': 'Username'}), max_length=50, required=True)

    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'prompt srch_explore'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Password', 'class': 'prompt srch_explore'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'prompt srch_explore'}))
    # email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

profiles/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import resolve, reverse
from django.views import View

from posts.models import Post, Follow, Stream
from .forms import EditProfileForm, UserRegisterForm
from .models import Profile


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            # Profile.get_or_create(user=request.user)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hurray your account was created!!')

            # Automatically Log In The User
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'], )
            login(request, new_user)

            return redirect('posts:home')



    elif request.user.is_authenticated:
        return redirect('posts:home')
    else:
        form = UserRegisterForm()
    context = {
        'form': form,
    }
    return render(request, 'user/sign-up.html', context)


def UserProfile(request, username):
    Profile.objects.get_or_create(user=request.user)
    user = get_object_or_404(User, username=username)
    profile = Profile.objects.get(user=user)
    url_name = resolve(request.path).url_name
    posts = Post.objects.filter(user=user).order_by('-posted')

    if url_name == 'profile':
        posts = Post.objects.filter(user=user).order_by('-posted')
    else:
        posts = profile.favourite.all()

    # Profile Stats
    posts_count = Post.objects.filter(user=user).count()
    following_count = Follow.objects.filter(follower=user).count()
    followers_count = Follow.objects.filter(following=user).count()
    # count_comment = Comment.objects.filter(post=posts).count()
    follow_status = Follow.objects.filter(following=user, follower=request.user).exists()

    # pagination
    paginator = Paginator(posts, 8)
    page_number = request.GET.get('page')
    posts_paginator = paginator.get_page(page_number)

    context = {
        'posts': posts,
        'profile': profile,
        'posts_count': posts_count,
        'following_count': following_count,
        'followers_count': followers_count,
        'posts_paginator': posts_paginator,
        'follow_status': follow_status,
        # 'count_comment':count_comment,
    }
    return render(request, 'user/profile.html', context)


def follow(request, username, option):
    user = request.user
    following = get_object_or_404(User, username=username)

    try:
        f, created = Follow.objects.get_or_create(follower=request.user, following=following)

        if int(option) == 0:
            f.delete()
            Stream.objects.filter(following=following, user=request.user).all().delete()
        else:
            posts = Post.objects.all().filter(user=following)[:25]
            with transaction.atomic():
                for post in posts:
                    stream = Stream(post=post, user=request.user, date=post.posted, following=following)
                    stream.save()
        return HttpResponseRedirect(reverse('profiles:profile', args=[username]))

    except User.DoesNotExist:
        return HttpResponseRedirect(reverse('profiles:profile', args=[username]))

def EditProfile(request):
    user = request.user.id
    profile = Profile.objects.get(user__id=user)

    if request.method == "POST":
        form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            profile.image = form.cleaned_data.get('image')
            profile.first_name = form.cleaned_data.get('first_name')
            profile.last_name = form.cleaned_data.get('last_name')
            profile.location = form.cleaned_data.get('location')
            profile.url = form.cleaned_data.get('url')
            profile.bio = form.cleaned_data.get('bio')
            profile.save()
            return redirect('profiles:profile', profile.user.username)
    else:
        form = EditProfileForm(instance=request.user.profile)

    context = {
        'form':form,
    }
    return render(request, 'user/editprofile.html', context)

templates/user/editprofile.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br><br>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram Login Form</title>
</head>

<body>

  <div id="wrapper">
    <div class="container">
      <div class="phone-app-ddemo"></div>
      <div class="form-data">
        <form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
          <div class="logo">
            <h3 style="padding: 20px; font-size: 20px;">Edit Profile</h3>
          </div>
          {{form.image}} <br>
		  {{form.first_name}} <br>
		  {{form.last_name}} <br>
		  {{form.bio}} <br>
		  {{form.location}} <br>
		  {{form.url}} <br>
          <button class="form-btn" type="submit">Update Profile</button>
          <!-- <a href="index.html" class="form-btn" type="submit">Log in</a> -->
          
        </form>
        
      </div>
    </div>

    <footer>
      <div class="container">
        <nav class="footer-nav">
          <ul>
            <li>
              <a href="#">About us</a>
            </li>
            <li>
              <a href="#">Support</a>
            </li>
            <li>
              <a href="#">Press</a>
            </li>
            <li>
              <a href="#">Api</a>
            </li>
            <li>
              <a href="#">Jobs</a>
            </li>
            <li>
              <a href="#">Privacy</a>
            </li>
            <li>
              <a href="#">Terms</a>
            </li>
            <li>
              <a href="#">Directory</a>
            </li>
            <li>
              <a href="#">Profiles</a>
            </li>
            <li>
              <a href="#">Hashtags</a>
            </li>
            <li>
              <a href="#">Languages</a>
            </li>
          </ul>
        </nav>
        <div class="copyright-notice">
          &copy 2023 Instagram
        </div>
      </div>
    </footer>

  </div>

</body>

</html>
{% endblock content %}

templates/user/profile.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Profile Page{% endblock %}
{% block content %}
<head>


    <link rel="stylesheet" href="{% static 'assets3/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'assets3/css/styles.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">

</head>
<body>

    <header>
        <br><br><br>
        <div class="container">

            <div class="profile">

                <div class="profile-image">

                    <img src="{{profile.image.url}}" alt="" style="width: 200px; height: 200px;">

                </div>

                <div class="profile-user-settings">
                        {% if profile.first_name %}
                        <h6 class="profile-user-name">{{profile.first_name}} {{profile.last_name}}</h6> <br> <br>
                        {% endif %}
                        <h5 style="font-size: 15px;" class="profile-user-name">@{{profile.user.username}}</h5> <br> <br>

                        {% if request.user.is_authenticated and request.user == profile.user %}
                        <a style="text-decoration: none;" href="{% url 'profiles:editprofile' %}" class="btn profile-edit-btn">Edit Profile</a>
                        <a style="text-decoration: none;" href="{% url 'profiles:sign-out' %}" class="btn profile-edit-btn">Logout</a>
                        <button class="btn profile-settings-btn" aria-label="profile settings"><i class="fas fa-cog" aria-hidden="true"></i></button>

                        
                        {% endif %}
                        <br><br>
                        {% if request.user.is_authenticated and request.user != profile.user %}
                            {% if follow_status == True %}
                                <a href="{% url 'profiles:follow' profile.user 0 %}" class="btn profile-edit-btn" style="color: red;">Unfollow</a> <br><br>
                            {% else %}
                                <a href="{% url 'profiles:follow' profile.user 1 %}" class="btn profile-edit-btn" style="color: green;">Follow</a> <br><br>
                            {% endif %}
                        {% endif %}

                        {% if request.user.is_authenticated and request.user != profile.user %}
                                <a href="{% url 'directs:conversation' profile.user  %}" class="btn profile-edit-btn">Message</a> <br><br>
                        {% endif %}
                        <br>

                    
                    
                    
                    

                </div>

                

                <div class="profile-bio">
                    <br>
                    {% if profile.bio %}
                    <p><span class="profile-real-name"></span>◉ {{profile.bio}}</p>
                    {% endif %}
                    {% if profile.location %}
                    <p><span class="profile-real-name"></span>◉ {{profile.location}}</p>
                    {% endif %}
                    {% if profile.url %}
                    <p><span class="profile-real-name"></span>◉ <a href="{{profile.url}}">{{profile.url}}</a></p>
                    {% endif %}
                    <br><br>
                    <div class="profile-user-settings" style="margin-bottom:6mm">
                        <a  href="{% url 'profiles:profile' profile.user %}"  class="btn profile-edit-btn">Posts</a>
                        {% if request.user == profile.user %}
                        <a  href="{% url 'profiles:profilefavourite' profile.user %}"  class="btn profile-edit-btn" >Saved</a>
                        {% endif %}
                    </div>
                </div>


                <div class="profile-stats">

                    <ul>
                        <li><span class="profile-stat-count">{{posts_count}}</span> posts</li>
                        <li><span class="profile-stat-count">{{followers_count}}</span> followers</li>
                        <li><span class="profile-stat-count">{{following_count}}</span> following</li>
                    </ul>
                    <br>
                    
                </div>

            </div>
            <!-- End of profile section -->

        </div>
        <!-- End of container -->

    </header>
    
    <main>

        <div class="container">

            <div class="gallery">
                
                {% for post in posts %}
                <a href="{{post.get_absolute_url}}"><div class="gallery-item" tabindex="0">

                    <img src="{{ post.picture.url }}" class="gallery-image" alt="" style="width: 500px; height: 300px; object-fit: cover;">

                    <div class="gallery-item-info">

                        <ul>
                            <li class="gallery-item-likes"><span class="visually-hidden">Likes:</span><i class="fas fa-heart" aria-hidden="true"></i> {{post.likes}}</li>
                            <li class="gallery-item-comments"><span class="visually-hidden">Comments:</span><i class="fas fa-comment" aria-hidden="true"></i> {{post.comment.count}}</li>
                        </ul>

                    </div>

                </div></a>
                {% endfor %}

                

                

            </div>
            <!-- End of gallery -->


        </div>
        <!-- End of container -->

    </main>
    {% endblock content %}

templates/user/sign-in.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram | Login </title>
</head>

<body>

  <div id="wrapper">
    <div class="container">
      <div class="phone-app-demo"></div>
      <div class="form-data">
        <form action="" method="POST">{% csrf_token %}
          <div class="logo">
            <img src="{% static 'assets2/images/logo.png' %}" alt="logo">
          </div>
          <!-- <input type="text" placeholder="Phone number, username, or email"> -->
          <!-- <input type="password" placeholder="Password"> -->
          {{form}}
          <button class="form-btn" type="submit">Log in</button>
          <!-- <a href="index.html" class="form-btn" type="submit">Log in</a> -->
          <span class="has-separator">Or</span>
          <a class="facebook-login" href="#">
            <i class="fab fa-facebook-square"></i> Log in with Facebook
          </a>
          <a class="password-reset" href="#">Forgot password?</a>
        </form>
        <div class="sign-up">
          Don't have an account? <a href="{% url 'profiles:sign-up' %}">Sign up</a>
        </div>
        <div class="get-the-app">
          <span>Get the app.</span>
          <div class="badges">
                        <img src="{% static 'assets2/images/app-store.png' %}" alt="app-store badge">

            <img src="{% static 'assets2/images/google-play.png' %}" alt="google-play badge">

          </div>
        </div>
      </div>
    </div>
</body>

</html>

templates/user/sign-out.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram | Out</title>
</head>

<body>

  <div id="wrapper">
    <div class="container">
      <div class="phone-app-demo"></div>
      <div class="form-data">
        <form action="{% url 'profiles:sign-in' %}" method="post">
          <div class="logo">
            <img src="{% static 'assets2/images/logo.png' %}" alt="logo">
          </div>
          <input type="text" placeholder="Phone number, username, or email">
          <input type="password" placeholder="Password">
          <button class="form-btn" type="submit"><a href="{% url 'posts:home' %}" style="color: white;">Log in</a></button>

          <span class="has-separator">Or</span>
          <a class="facebook-login" href="#">
            <i class="fab fa-facebook-square"></i> Log in with Facebook
          </a>
          <a class="password-reset" href="#">Forgot password?</a>
        </form>
        <div class="sign-up">
          Don't have an account? <a href="{% url 'profiles:sign-up' %}">Sign up</a>
        </div>
        <div class="get-the-app">
          <span>Get the app.</span>
          <div class="badges">
            <img src="{% static 'assets2/images/app-store.png' %}" alt="app-store badge">
            <img src="{% static 'assets2/images/google-play.png' %}" alt="google-play badge">
          </div>
        </div>
      </div>
    </div>



  </div>

</body>

</html>

templates/user/sign-up.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
  <link rel="stylesheet" href="{% static 'assets2/style.css' %}">
  <title>Instagram | Register</title>
</head>

<body>

  <div id="wrapper">
    <div class="container">
      <div class="phone-app-demo"></div>
      <div class="form-data">
        <form action="{% url 'profiles:sign-up' %}" method="POST">
          {% csrf_token %}
          <div class="logo">
            <img src="{% static 'assets2/images/logo.png' %}" alt="logo">
          </div>

          {{form.username}}
          {{form.email}}
          {{form.password1}}
          {{form.password2}}
          <button class="form-btn" type="submit">Register</button>


          <!-- <a href="index.html" class="form-btn" type="submit">Log in</a> -->

        </form>
        <div class="sign-up">
            Have an account? <a href="{% url 'profiles:sign-in' %}">Sign In</a>
        </div>
        <div class="get-the-app">
          <span>Get the app.</span>
          <div class="badges">
            <img src="{% static 'assets2/images/app-store.png' %}" alt="app-store badge">
            <img src="{% static 'assets2/images/google-play.png' %}" alt="google-play badge">
          </div>
        </div>
      </div>
    </div>


  </div>

</body>

</html>